### ISSUE TITLE
context menu button during video play

### ISSUE THREAD

**Issue by monkz** [mizaki/awxi#4]
If i play a movie, i can't use awxi's remotecontrol "context menu" button, although it works in file selection listings.
It prevents me to get to the subtitle selection.

But anyway - best webinterface for kodi fitting my needs ;)

**Comment by mizaki** [comment]
There isn't really a context menu when playing a movie. If you use the return/enter that will bring up the menu I think you are after.

**Comment by monkz** [comment]
This is similar in with music:
https://www.youtube.com/watch?v=NcogPuSo-DU#t=358 from 5:57 to 6:07
The first overlay is reachable via "Information",  the second (with buttons) is not available.

Return/enter has no effect during a movie.

**Comment by mizaki** [comment]
Pressing the "enter/return" icon should bring up the menu. It works for me. Should be the same for audio. It should also work if you press return on the actual PC Kodi is running on.

**Comment by monkz** [comment]
Hm strange.
During a movie return/enter button and contextmenu button have no effect for me.
If i'm in a normal menu (like Kodi homescreen) return/enter button and contextmenu button have effect.
Hitting enter on the keyboard connected to my Raspi2 works in both situations.

Maybe some useful infos:
I have Version 0.7.5 of AVXi on Kodi on OSMC.
My machine runs Arch Linux with Firefox + NoScript (but all scripts are allowed)
Same on SailfishOS Browser without NoScript

**Comment by monkz** [comment]
Ah i was mistaken about osd and context menu, because Kodimote https://github.com/RobertMe/kodimote uses the context menu button to send both commands. But i punched all keys ob my keyboard - still no osd.

**Comment by monkz** [comment]
I don't know if this even works: monkz@c2064c7e547911bb61a83185b16c1542101d08ce
